/*CREATE TABLE PROFILES*/

CREATE TABLE PROFILES
(
    ID             INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN          VARCHAR(55) NOT NULL UNIQUE,
    PASSWORD       VARCHAR(55) NOT NULL,
    PROFILE_ENABLE BOOLEAN
);

/*CREATE TABLE USERS*/

CREATE TABLE USERS
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(55),
    SURNAME    VARCHAR(55),
    PROFILE_ID INT UNIQUE,
    EMAIL      VARCHAR(55) UNIQUE,
    CONSTRAINT FK_PROFILE_ID
        FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES (ID)
);

/*CREATE TABLE ROLES*/

CREATE TABLE ROLES
(
    ID    INT AUTO_INCREMENT PRIMARY KEY,
    ROLE VARCHAR(55) NOT NULL UNIQUE
);

/*CREATE TABLE USERS_ROLES*/

CREATE TABLE USERS_ROLES
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    CONSTRAINT FK_USER_ID
        FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_ROLE_ID
        FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);

/*CREATE TABLE TASKS*/

CREATE TABLE TASKS
(
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION     VARCHAR(255) NOT NULL,
    DATE_SUBMISSION TIMESTAMP NOT NULL,
    EXECUTION_DATE  TIMESTAMP NOT NULL,
    USER_ID         INT NOT NULL,
    COMPLETED       BOOLEAN,
    DELETED         BOOLEAN,
    CONSTRAINT FK_TASKS_USER_ID
        FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

/*CREATE TABLE FILES*/

CREATE TABLE FILES
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    PATH    VARCHAR(255) NOT NULL UNIQUE,
    TASK_ID INT NOT NULL,
    CONSTRAINT FK_TASK_ID
        FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID)
);