/*ADD ALL ADMIN(ROLE)*/
INSERT  INTO ROLES(ID, ROLE) VALUES (ROLE_ID_SEQ_GEN.NEXTVAL, 'ADMIN');

/*USER#1*/
INSERT INTO USERS (ID, NAME, SURNAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'Aliaksei', 'Kakora', 'AKAKORA@YANDEX.BY');
INSERT INTO PROFILES (ID, LOGIN, PASSWORD, IS_ENABLE) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'kakora', '1', 'TRUE');
INSERT INTO ROLE_USER(ROLE_ID, USER_ID) VALUES (ROLE_ID_SEQ_GEN.CURRVAL, USER_ID_SEQ_GEN.CURRVAL);
INSERT INTO TASKS (ID, NAME, DESCRIPTION, DATE_ADDED, DATE_COMPLETION, USER_ID, COMPLETED, DELETED) VALUES (TASK_ID_SEQ_GEN.NEXTVAL,'learning java EE', 'learning java EE in IT-academy', '2020-12-08 18:00:00', '2021-05-01 12:00:00', USER_ID_SEQ_GEN.CURRVAL, FALSE, FALSE);
INSERT INTO TASKS (ID, NAME, DESCRIPTION, DATE_ADDED, DATE_COMPLETION, USER_ID, COMPLETED, DELETED) VALUES (TASK_ID_SEQ_GEN.NEXTVAL,'task2', 'learning java EE in IT-academy', '2020-12-08 18:00:00', '2021-05-01 12:00:00', USER_ID_SEQ_GEN.CURRVAL, FALSE, FALSE);
INSERT INTO TASKS (ID, NAME, DESCRIPTION, DATE_ADDED, DATE_COMPLETION, USER_ID, COMPLETED, DELETED) VALUES (TASK_ID_SEQ_GEN.NEXTVAL,'task3', 'learning java EE in IT-academy', '2020-12-08 18:00:00', '2021-05-01 12:00:00', USER_ID_SEQ_GEN.CURRVAL, FALSE, FALSE);
/*ADD ALL USER(ROLE)*/
INSERT  INTO ROLES(ID, ROLE) VALUES (ROLE_ID_SEQ_GEN.NEXTVAL, 'USER');
INSERT INTO ROLE_USER(ROLE_ID, USER_ID) VALUES (ROLE_ID_SEQ_GEN.CURRVAL,USER_ID_SEQ_GEN.CURRVAL);

/*USER#2*/
INSERT INTO USERS (ID, NAME, SURNAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'Maxim', 'Bondarev', 'BOMDAREV@GMAIL.COM');
INSERT INTO PROFILES (ID, LOGIN, PASSWORD, IS_ENABLE) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'bondarev', '1', 'TRUE');
INSERT INTO ROLE_USER(ROLE_ID, USER_ID) VALUES (ROLE_ID_SEQ_GEN.CURRVAL,USER_ID_SEQ_GEN.CURRVAL);
INSERT INTO TASKS (ID, NAME, DESCRIPTION, DATE_ADDED, DATE_COMPLETION, USER_ID, COMPLETED, DELETED) VALUES (TASK_ID_SEQ_GEN.NEXTVAL,'learning java EE', 'learning java EE in IT-academy', '2020-12-08 18:00:00', '2021-05-01 12:00:00', USER_ID_SEQ_GEN.CURRVAL, FALSE, FALSE);
INSERT INTO MESSAGES(ID, MESSAGE, DATE_ADDED, USER_ID) VALUES (MESSAGE_ID_SEQ_GEN.NEXTVAL, 'TESTMESSAGE', '2021-3-18 18:29:00', USER_ID_SEQ_GEN.CURRVAL);
/*USER#3*/
INSERT INTO USERS (ID, NAME, SURNAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'АНДРЕЙ', 'ДМИТРИЕВ', 'MOHNATISHMEL@GMAIL.COM');
INSERT INTO PROFILES (ID, LOGIN, PASSWORD, IS_ENABLE) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'dmitriev', '1', 'FALSE');
INSERT INTO ROLE_USER(ROLE_ID, USER_ID) VALUES (ROLE_ID_SEQ_GEN.CURRVAL,USER_ID_SEQ_GEN.CURRVAL);
INSERT INTO TASKS (ID, NAME, DESCRIPTION, DATE_ADDED, DATE_COMPLETION, USER_ID, COMPLETED, DELETED) VALUES (TASK_ID_SEQ_GEN.NEXTVAL,'learning java EE', 'learning java EE in IT-academy', '2020-12-08 18:00:00', '2021-05-01 12:00:00', USER_ID_SEQ_GEN.CURRVAL, FALSE, FALSE);